In [61]:
# Import dependecies
import pandas as pd
import numpy as np
import difflib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [62]:
movies_df = pd.read_csv('../data/movies.csv')
movies_df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [63]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [64]:
movies_df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [65]:
selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director', 'production_companies']

In [66]:
# Replacing null values with null string
for feature in selected_features:
    movies_df[feature] = movies_df[feature].fillna('')


In [67]:
# combining all the selected_features
combined_df = movies_df['genres'] + movies_df['keywords'] + movies_df['tagline'] + movies_df['cast'] + movies_df['director'] + movies_df['production_companies']
combined_df

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object

In [68]:
vectorizer = TfidfVectorizer()

In [69]:
feature_vectors = vectorizer.fit_transform(combined_df)
print(feature_vectors)

  (0, 5300)	0.06658757622152417
  (0, 5506)	0.07719799906673884
  (0, 14900)	0.10006023738585378
  (0, 29328)	0.08429846010963403
  (0, 15290)	0.2323090586057348
  (0, 10029)	0.18492298683739533
  (0, 16317)	0.13828194096156365
  (0, 30556)	0.28384313631066155
  (0, 34479)	0.11065020650212594
  (0, 10280)	0.2032544217247949
  (0, 30393)	0.2323090586057348
  (0, 32012)	0.05976314733592446
  (0, 35360)	0.10525869838053162
  (0, 25214)	0.07178881654153738
  (0, 25680)	0.18084621464621511
  (0, 28984)	0.1325320943157888
  (0, 35384)	0.1991776495336147
  (0, 35803)	0.16771711203655737
  (0, 28947)	0.18280612374528368
  (0, 30031)	0.17141335003368377
  (0, 34703)	0.16659155194999575
  (0, 30947)	0.13645730924289162
  (0, 21140)	0.18974478492108335
  (0, 23447)	0.13314716087943707
  (0, 28145)	0.2323090586057348
  :	:
  (4801, 18861)	0.3167733394535455
  (4802, 24545)	0.05842367547021673
  (4802, 19078)	0.05842367547021673
  (4802, 14163)	0.06321137598988995
  (4802, 15612)	0.0587922955441139

In [70]:
# Cosine Similarity: getting the similarity confidence value
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.0683712  0.03194165 ... 0.02178793 0.         0.02108254]
 [0.0683712  1.         0.03873024 ... 0.02164503 0.         0.01241619]
 [0.03194165 0.03873024 1.         ... 0.01367098 0.         0.01068244]
 ...
 [0.02178793 0.02164503 0.01367098 ... 1.         0.         0.01118443]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.02108254 0.01241619 0.01068244 ... 0.01118443 0.         1.        ]]


In [98]:
# Getting input from user
movie_name = input('Enter your favorite movie name: ')

In [99]:
movie_name

'iron man'

In [100]:
# Create a list with all the list of the movie names given in the dataset
list_of_all_titles = movies_df['title'].tolist()

In [101]:
find_close_matches = difflib.get_close_matches(movie_name, list_of_all_titles)
find_close_matches

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [102]:
close_match = find_close_matches[0]

In [103]:
idx_of_movie = movies_df[movies_df.title == close_match]['index'].values[0]
idx_of_movie

68

In [104]:
similarity_score = list(enumerate(similarity[idx_of_movie]))
similarity_score

[(0, 0.01870487389262572),
 (1, 0.03225512638880382),
 (2, 0.010331365352332575),
 (3, 0.012380130064104568),
 (4, 0.015551193399824836),
 (5, 0.06163437346283479),
 (6, 0.05898357323657693),
 (7, 0.22577234055075063),
 (8, 0.0038799130693242864),
 (9, 0.03287689007171704),
 (10, 0.019432999457830454),
 (11, 0.006680273613451142),
 (12, 0.005210287734264375),
 (13, 0.012267297239736217),
 (14, 0.041510756657236955),
 (15, 0.019771360155222954),
 (16, 0.28486218582920136),
 (17, 0.00975374924437847),
 (18, 0.017564384938725447),
 (19, 0.011336361047799502),
 (20, 0.12906754137743545),
 (21, 0.010913747791312099),
 (22, 0.0065396658327832955),
 (23, 0.005938533965460444),
 (24, 0.006317640418819741),
 (25, 0.00544423882971361),
 (26, 0.22770163245236325),
 (27, 0.017283316022393934),
 (28, 0.06318277143266668),
 (29, 0.007801903974877902),
 (30, 0.13223321441873562),
 (31, 0.3211295673828924),
 (32, 0.022604946324748784),
 (33, 0.1304234958325037),
 (34, 0.017174823579782696),
 (35, 0.05

In [105]:
sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)
sorted_similar_movies

[(68, 0.9999999999999999),
 (79, 0.32787447484108667),
 (31, 0.3211295673828924),
 (16, 0.28486218582920136),
 (26, 0.22770163245236325),
 (7, 0.22577234055075063),
 (85, 0.2238034320667075),
 (174, 0.19198044255554492),
 (129, 0.1860530001633578),
 (182, 0.180385636664786),
 (169, 0.16740819109195565),
 (46, 0.16114259924574684),
 (126, 0.15928768459578535),
 (511, 0.14544550460707284),
 (38, 0.14528828192214271),
 (4401, 0.1447961206393833),
 (203, 0.1440543803632236),
 (94, 0.1425296954809988),
 (64, 0.14080693710184097),
 (788, 0.1368270089504856),
 (30, 0.13223321441873562),
 (33, 0.1304234958325037),
 (20, 0.12906754137743545),
 (101, 0.12752850782274786),
 (805, 0.1229209678349397),
 (232, 0.11065875843474386),
 (954, 0.1066092234247967),
 (242, 0.10469838235406062),
 (122, 0.10335635955998977),
 (3623, 0.10070098454512297),
 (353, 0.0931048705354273),
 (1210, 0.09211229532272641),
 (1740, 0.08527542083224902),
 (1406, 0.08287062162052608),
 (39, 0.08186280627367605),
 (1282, 0.

In [109]:
print('Movies suggested for you: \n')

i = 1
for i in range(30):
    index = sorted_similar_movies[i][0]
    title_from_index = movies_df[movies_df.index == index]['title'].values[0]
    print(f'{i} : {title_from_index}')

Movies suggested for you: 

0 : Iron Man
1 : Iron Man 2
2 : Iron Man 3
3 : The Avengers
4 : Captain America: Civil War
5 : Avengers: Age of Ultron
6 : Captain America: The Winter Soldier
7 : The Incredible Hulk
8 : Thor
9 : Ant-Man
10 : Captain America: The First Avenger
11 : X-Men: Days of Future Past
12 : Thor: The Dark World
13 : X-Men
14 : The Amazing Spider-Man 2
15 : The Helix... Loaded
16 : X2
17 : Guardians of the Galaxy
18 : X-Men: Apocalypse
19 : Deadpool
20 : Spider-Man 2
21 : X-Men: The Last Stand
22 : The Amazing Spider-Man
23 : X-Men: First Class
24 : Ghost Rider: Spirit of Vengeance
25 : The Wolverine
26 : The Judge
27 : Fantastic Four
28 : X-Men Origins: Wolverine
29 : Made


In [111]:
# Single Function
def recommend_movie(movie_name):
    list_of_all_titles = movies_df['title'].tolist()
    find_close_matches = difflib.get_close_matches(movie_name, list_of_all_titles)
    close_match = find_close_matches[0]
    idx_of_movie = movies_df[movies_df.title == close_match]['index'].values[0]

    similarity_score = list(enumerate(similarity[idx_of_movie]))
    sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

    print('Movies suggested for you: \n')

    i = 1
    for i in range(30):
        index = sorted_similar_movies[i][0]
        title_from_index = movies_df[movies_df.index == index]['title'].values[0]
        print(f'{i} : {title_from_index}')


recommend_movie(movie_name = input('Enter your favorite movie name: '))
    

Movies suggested for you: 

0 : Avatar
1 : X-Men: First Class
2 : Rise of the Planet of the Apes
3 : Dragonball Evolution
4 : Alien
5 : The Watch
6 : Eragon
7 : Fantastic 4: Rise of the Silver Surfer
8 : Live Free or Die Hard
9 : X-Men Origins: Wolverine
10 : Australia
11 : X-Men: The Last Stand
12 : Titanic
13 : The Heat
14 : The Abyss
15 : Alien³
16 : Percy Jackson & the Olympians: The Lightning Thief
17 : Aliens
18 : Sunshine
19 : Wall Street: Money Never Sleeps
20 : True Lies
21 : Life of Pi
22 : The Book of Life
23 : Night at the Museum
24 : Parental Guidance
25 : Gulliver's Travels
26 : Mr. Popper's Penguins
27 : Aliens vs Predator: Requiem
28 : The Devil Wears Prada
29 : Planet of the Apes
